// frontend/src/components/layout/Sidebar.tsx
import { useMemo, useState } from "react";
import {
  Activity,
  BookOpen,
  Globe,
  HardDriveDownload,
  Hash,
  Heart,
  Layers,
  LayoutDashboard,
  MessageSquare,
  Plus,
  Settings as SettingsIcon,
  Shield,
  User,
  Users,
} from "lucide-react";
import { useAccountStore } from "../../stores/useAccountStore";
import { useMainViewStore } from "../../stores/useMainViewStore";
import { useMitmStatusStore } from "../../stores/useMitmStatusStore";
import { useSettingsStore } from "../../stores/useSettingsStore";
import { showErrorToast, showToast } from "../../utils/toast";
import { PRIMARY_POOL_LABEL, type ShellViewTab } from "../../utils/appMode";

interface MenuItem {
  id: ShellViewTab;
  icon: typeof Users;
  label: string;
}

const MENU_ITEMS: MenuItem[] = [
  { id: "Dashboard", icon: LayoutDashboard, label: "总览" },
  { id: "Accounts", icon: Users, label: PRIMARY_POOL_LABEL },
  { id: "Providers", icon: Layers, label: "提供商" },
  { id: "Usage", icon: Activity, label: "用量统计" },
  { id: "Relay", icon: Globe, label: "OpenAI Relay" },
  { id: "Cleanup", icon: HardDriveDownload, label: "清理优化" },
  { id: "Settings", icon: SettingsIcon, label: "MITM 设置" },
];

/**
 * Sidebar — Vue 1:1 完整迁移：导航 + MITM 概况卡（号池总数 / 当前活跃 Key /
 * 当前活跃账号 / 绑定对话 / 健康度）+ Help/About 入口。
 */
export default function Sidebar() {
  const activeTab = useMainViewStore((s) => s.activeTab);
  const setActiveTab = useMainViewStore((s) => s.setActiveTab);

  const accounts = useAccountStore((s) => s.accounts);
  const status = useMitmStatusStore((s) => s.status);
  const settings = useSettingsStore((s) => s.settings);
  const updateSettings = useSettingsStore((s) => s.updateSettings);

  // ── 路由模式胶囊：号池 ↔ 提供商 ──
  const routeMode: 'pool' | 'providers' =
    (settings as any)?.mitm_route_mode === 'providers' ? 'providers' : 'pool';
  const [switchingRouteMode, setSwitchingRouteMode] = useState(false);
  const setRouteMode = async (target: 'pool' | 'providers') => {
    if (routeMode === target || switchingRouteMode || !settings) return;
    setSwitchingRouteMode(true);
    try {
      await updateSettings({ ...settings, mitm_route_mode: target } as any);
      showToast(
        target === 'providers'
          ? '已切到提供商: MITM chat 走已激活卡片'
          : '已切回 Windsurf 号池接管',
        'success',
      );
    } catch (e: unknown) {
      showErrorToast(e, '切换路由模式失败');
    } finally {
      setSwitchingRouteMode(false);
    }
  };

  const activeKey = useMemo(
    () => status?.pool_status?.find((item) => item.is_current) ?? null,
    [status],
  );

  // 0.2: 合并 activeSummary + activeAccountLabel 为一个完整展示：
  // 主行优先 nickname > email > key_short。双信息时（nickname 与 email 均有）附副行。
  // hash 仅在 hover title 里出现，调试用。
  const activeKeyShort = String(activeKey?.key_short || "").trim();
  const activeNickname = String(activeKey?.nickname || "").trim();
  const activeEmail = String(activeKey?.email || "").trim();
  const activePrimary = activeNickname || activeEmail || activeKeyShort;
  const activeSecondary =
    activeNickname && activeEmail ? activeEmail : "";
  const activeSummary = activePrimary || "等待活跃 Key";

  const boundSessions = useMemo(() => {
    const sessions = status?.active_sessions ?? [];
    const currentHash = activeKey?.key_hash ?? "";
    const currentShort = activeKey?.key_short ?? "";
    if (!currentHash && !currentShort) return [];
    return sessions.filter((s) => {
      if (currentHash && s.pool_key_hash) {
        return s.pool_key_hash === currentHash;
      }
      return s.pool_key_short === currentShort;
    });
  }, [status, activeKey]);

  const healthyCount =
    status?.pool_status?.filter((item) => item.healthy).length ?? 0;
  const totalCount = status?.pool_status?.length ?? 0;

  return (
    <nav className="w-60 h-full ios-glass border-r border-ios-divider dark:border-ios-dividerDark flex flex-col pt-6 pb-6 z-40 shrink-0 overflow-y-auto">
      <div className="px-5 pb-2 mb-2 text-xs font-semibold uppercase text-ios-textSecondary dark:text-ios-textSecondaryDark tracking-wider">
        导航
      </div>
      <ul className="space-y-1.5 px-3">
        {MENU_ITEMS.map((item) => {
          const Icon = item.icon;
          const active = activeTab === item.id;
          return (
            <li key={item.id}>
              <button
                type="button"
                className={[
                  "no-drag-region",
                  "w-full flex items-center px-4 py-2.5 rounded-[14px] text-[14px] transition-all duration-[250ms] font-medium ios-btn",
                  active
                    ? "bg-gradient-to-b from-[#3b82f6] to-ios-blue text-white shadow-md shadow-ios-blue/25 ring-1 ring-black/5 dark:ring-white/10 ring-inset"
                    : "text-ios-text dark:text-ios-textDark hover:bg-black/5 dark:hover:bg-white/10",
                ].join(" ")}
                onClick={() => setActiveTab(item.id)}
              >
                <Icon
                  className={`w-5 h-5 mr-3 transition-opacity duration-300 ${
                    active ? "opacity-100" : "opacity-70"
                  }`}
                  strokeWidth={2.2}
                />
                {item.label}
              </button>
            </li>
          );
        })}
      </ul>

      <div className="mx-3 mt-4 rounded-[18px] border border-black/[0.05] bg-white/60 px-4 py-4 shadow-[0_8px_24px_rgba(15,23,42,0.06)] dark:border-white/[0.06] dark:bg-white/[0.04]">
        <div className="text-[11px] font-bold uppercase tracking-[0.22em] text-ios-textSecondary dark:text-ios-textSecondaryDark">
          MITM 概况
        </div>
        <div className="mt-3 flex items-center justify-between">
          <div>
            <div className="text-[20px] font-extrabold leading-none text-ios-text dark:text-ios-textDark">
              {accounts.length}
            </div>
            <div className="mt-1 text-[11px] font-medium text-ios-textSecondary dark:text-ios-textSecondaryDark">
              号池总数
            </div>
          </div>
          <span className="rounded-full bg-ios-blue/10 px-2.5 py-1 text-[10px] font-bold tracking-wide text-ios-blue">
            Pure MITM
          </span>
        </div>

        <div
          className="mt-3 rounded-[14px] bg-black/[0.03] px-3 py-2 text-[11px] font-medium text-ios-textSecondary dark:bg-white/[0.05] dark:text-ios-textSecondaryDark"
          title={activeKeyShort || activeSummary}
        >
          当前活跃账号
          <div className="mt-1 flex items-center gap-1.5">
            {activePrimary && activePrimary !== "等待活跃 Key" ? (
              <User className="h-3 w-3 shrink-0 text-ios-blue" strokeWidth={2.4} />
            ) : null}
            <span className="truncate text-[12px] font-semibold text-ios-text dark:text-ios-textDark">
              {activeSummary}
            </span>
          </div>
          {activeSecondary ? (
            <div
              className="mt-0.5 truncate text-[10px] font-medium opacity-80"
              title={activeSecondary}
            >
              {activeSecondary}
            </div>
          ) : null}
        </div>

        {boundSessions.length > 0 ? (
          <div className="mt-2 rounded-[14px] bg-black/[0.02] px-3 py-2 dark:bg-white/[0.03]">
            <div className="flex items-center gap-1 text-[10px] font-bold uppercase tracking-[0.15em] text-ios-textSecondary dark:text-ios-textSecondaryDark mb-1.5">
              <MessageSquare className="h-3 w-3 shrink-0" strokeWidth={2.2} />
              绑定对话 ({boundSessions.length})
            </div>
            <ul className="space-y-1">
              {boundSessions.map((session) => {
                // 0.3: 优先 title（对话名），fallback 到 conv_id_short hash。
                const title = String(session.title || "").trim();
                const display = title || session.conv_id_short;
                const isHash = !title;
                return (
                  <li
                    key={session.conv_id_short}
                    className="flex items-center gap-1.5 text-[10px] text-ios-text dark:text-ios-textDark"
                  >
                    <Hash className="h-3 w-3 shrink-0 opacity-40" strokeWidth={2} />
                    <span
                      className={`truncate ${isHash ? "font-mono" : ""}`}
                      title={
                        title
                          ? `${title}　·　${session.conv_id_short}`
                          : session.conv_id_short
                      }
                    >
                      {display}
                    </span>
                    <span className="ml-auto shrink-0 text-[9px] text-ios-textSecondary dark:text-ios-textSecondaryDark">
                      {session.request_count}次
                    </span>
                  </li>
                );
              })}
            </ul>
          </div>
        ) : null}

        {/* 1.6: 空号池 → 醒目 CTA；非空 → 健康统计 */}
        {accounts.length === 0 ? (
          <button
            type="button"
            className="no-drag-region mt-3 flex w-full items-center justify-center gap-1.5 rounded-[14px] bg-gradient-to-b from-[#3b82f6] to-ios-blue px-3 py-2 text-[12px] font-bold text-white shadow-md shadow-ios-blue/25 ring-1 ring-black/5 ring-inset transition-transform ios-btn hover:-translate-y-px"
            onClick={() => useMainViewStore.getState().openImportModal()}
            title="粘贴 API Key / JWT / 邮箱密码批量导入"
          >
            <Plus className="h-3.5 w-3.5" strokeWidth={2.6} />
            立即导入第一个账号
          </button>
        ) : (
          <div className="mt-3 flex items-center gap-2 rounded-[14px] border border-emerald-500/12 bg-emerald-500/[0.06] px-3 py-2 text-[11px] font-medium text-emerald-700 dark:text-emerald-300">
            <Shield className="h-3.5 w-3.5 shrink-0" strokeWidth={2.4} />
            健康 {healthyCount} / {totalCount}
          </div>
        )}

        {/* ★ 路由模式胶囊：号池 ↔ 提供商(iOS 风滑动指示条) */}
        <div
          className="no-drag-region relative mt-2 flex items-stretch rounded-full border border-black/[0.06] bg-white/80 p-0.5 shadow-sm dark:border-white/[0.08] dark:bg-white/[0.05]"
          role="tablist"
        >
          <span
            className={`absolute top-0.5 bottom-0.5 left-0.5 rounded-full shadow-md transition-[transform,background-image,box-shadow] duration-[420ms] ease-[cubic-bezier(0.25,1,0.5,1)] ${
              routeMode === 'providers'
                ? 'bg-gradient-to-b from-violet-500 via-fuchsia-400 to-rose-300 shadow-fuchsia-500/25'
                : 'bg-gradient-to-b from-[#3b82f6] to-ios-blue shadow-ios-blue/25'
            }`}
            style={{
              width: 'calc(50% - 2px)',
              transform: routeMode === 'providers' ? 'translateX(calc(100% + 0px))' : 'translateX(0)',
            }}
          />
          <button
            type="button"
            className={`ios-btn relative z-10 flex-1 flex h-7 items-center justify-center gap-1 rounded-full text-[11px] font-bold transition-colors duration-200 ${
              routeMode === 'pool'
                ? 'text-white'
                : 'text-ios-textSecondary hover:text-ios-text dark:text-ios-textSecondaryDark dark:hover:text-ios-textDark'
            }`}
            disabled={switchingRouteMode}
            onClick={() => setRouteMode('pool')}
          >
            <Users className="h-3 w-3" strokeWidth={2.6} />
            号池
          </button>
          <button
            type="button"
            className={`ios-btn relative z-10 flex-1 flex h-7 items-center justify-center gap-1 rounded-full text-[11px] font-bold transition-colors duration-200 ${
              routeMode === 'providers'
                ? 'text-white'
                : 'text-ios-textSecondary hover:text-ios-text dark:text-ios-textSecondaryDark dark:hover:text-ios-textDark'
            }`}
            disabled={switchingRouteMode}
            onClick={() => setRouteMode('providers')}
          >
            <Globe className="h-3 w-3" strokeWidth={2.6} />
            提供商
          </button>
        </div>
      </div>

      <div className="mx-3 mt-3 flex gap-2">
        <button
          type="button"
          className={`no-drag-region flex-1 flex items-center justify-center gap-1.5 py-2 rounded-[12px] text-[12px] font-bold transition-all ios-btn ${
            activeTab === "Help"
              ? "bg-ios-blue text-white shadow-sm"
              : "bg-black/[0.04] text-gray-600 dark:bg-white/[0.06] dark:text-gray-400 hover:bg-black/[0.08] dark:hover:bg-white/[0.1]"
          }`}
          onClick={() => setActiveTab("Help")}
        >
          <BookOpen className="h-3.5 w-3.5" strokeWidth={2.4} />
          帮助
        </button>
        <button
          type="button"
          className={`no-drag-region flex-1 flex items-center justify-center gap-1.5 py-2 rounded-[12px] text-[12px] font-bold transition-all ios-btn ${
            activeTab === "About"
              ? "bg-rose-500 text-white shadow-sm"
              : "bg-black/[0.04] text-gray-600 dark:bg-white/[0.06] dark:text-gray-400 hover:bg-black/[0.08] dark:hover:bg-white/[0.1]"
          }`}
          onClick={() => setActiveTab("About")}
        >
          <Heart className="h-3.5 w-3.5" strokeWidth={2.4} />
          关于
        </button>
      </div>
    </nav>
  );
}

// frontend/src/components/layout/Sidebar.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import { Activity, BookOpen, Globe, HardDriveDownload, Hash, Heart, Layers, LayoutDashboard, MessageSquare, Settings, Shield, User, Users } from 'lucide-vue-next'
import { useAccountStore } from '../../stores/useAccountStore'
import { useMitmStatusStore } from '../../stores/useMitmStatusStore'
import { useSettingsStore } from '../../stores/useSettingsStore'
import { showToast } from '../../utils/toast'
import { PRIMARY_POOL_LABEL, type ShellViewTab } from '../../utils/appMode'

const props = defineProps<{ activeTab: ShellViewTab }>()
const emit = defineEmits<{ (e: 'update:activeTab', tab: ShellViewTab): void }>()

const accountStore = useAccountStore()
const mitmStore = useMitmStatusStore()
const settingsStore = useSettingsStore()

// ── 路由模式胶囊:号池 ↔ 提供商 ──
// providers 模式下 MITM 把 IDE 的 cascade 请求翻译给已激活的 ProviderAccount。
const routeMode = computed<'pool' | 'providers'>(() => {
  const v = (settingsStore.settings as any)?.mitm_route_mode
  return v === 'providers' ? 'providers' : 'pool'
})
const switchingRouteMode = ref(false)
const setRouteMode = async (target: 'pool' | 'providers') => {
  if (routeMode.value === target || switchingRouteMode.value) return
  switchingRouteMode.value = true
  try {
    await settingsStore.updateSettings({
      ...(settingsStore.settings as any),
      mitm_route_mode: target,
    } as any)
    showToast(
      target === 'providers'
        ? '已切到提供商: MITM chat 走已激活卡片'
        : '已切回 Windsurf 号池接管',
      'success',
    )
  } catch (e: unknown) {
    showToast(`切换失败: ${String(e)}`, 'error')
  } finally {
    switchingRouteMode.value = false
  }
}

const menuItems = [
  { id: 'Dashboard', icon: LayoutDashboard, label: '总览' },
  { id: 'Providers', icon: Layers, label: '提供商' },
  { id: 'Accounts', icon: Users, label: PRIMARY_POOL_LABEL },
  { id: 'Usage', icon: Activity, label: '用量统计' },
  { id: 'Relay', icon: Globe, label: 'OpenAI Relay' },
  { id: 'Cleanup', icon: HardDriveDownload, label: '清理优化' },
  { id: 'Settings', icon: Settings, label: 'MITM 设置' },
] satisfies Array<{ id: ShellViewTab; icon: typeof Users; label: string }>

const footerModeLabel = computed(() => 'Pure MITM')

const activeKey = computed(() => mitmStore.status?.pool_status?.find((item) => item.is_current) ?? null)

const activeSummary = computed(() => {
  const key = String(activeKey.value?.key_short || '').trim()
  if (!key) {
    return '等待活跃 Key'
  }
  return key
})

const activeAccountLabel = computed(() => {
  const k = activeKey.value
  if (!k) return ''
  const nick = String(k.nickname || '').trim()
  const email = String(k.email || '').trim()
  if (nick && email) return `${nick} (${email})`
  return email || nick || ''
})

const boundSessions = computed(() => {
  const sessions = mitmStore.status?.active_sessions ?? []
  // 用 PoolKeyHash 精确匹配；长 token 类账号会让 PoolKeyShort 共享 16 字符
  // 前缀，跨账号过滤就会"看到不属于自己的会话"。pool_key_hash 是 sha256 前
  // 12 hex，不会撞车。后端兼容旧字段时退回 pool_key_short 全等匹配。
  const currentHash = activeKey.value?.key_hash ?? ''
  const currentShort = activeKey.value?.key_short ?? ''
  if (!currentHash && !currentShort) return []
  return sessions.filter((s) => {
    if (currentHash && s.pool_key_hash) {
      return s.pool_key_hash === currentHash
    }
    return s.pool_key_short === currentShort
  })
})
</script>

<template>
  <nav class="w-60 h-full ios-glass border-r border-ios-divider dark:border-ios-dividerDark flex flex-col pt-4 pb-4 z-40 shrink-0">
    <div class="px-5 pb-1 mb-1 text-[10px] font-semibold uppercase text-ios-textSecondary dark:text-ios-textSecondaryDark tracking-wider">
      导航
    </div>
    <ul class="flex-1 space-y-0.5 px-3">
      <li v-for="item in menuItems" :key="item.id">
        <button
          type="button"
          class="no-drag-region"
          @click="emit('update:activeTab', item.id)"
          :class="[
            'w-full flex items-center px-3 py-1.5 rounded-[12px] text-[13px] transition-all duration-[250ms] font-medium ios-btn',
            activeTab === item.id
              ? 'bg-gradient-to-b from-[#3b82f6] to-ios-blue text-white shadow-md shadow-ios-blue/25 ring-1 ring-black/5 dark:ring-white/10 ring-inset'
              : 'text-ios-text dark:text-ios-textDark hover:bg-black/5 dark:hover:bg-white/10'
          ]"
        >
          <component :is="item.icon" class="w-4 h-4 mr-2.5 transition-opacity duration-300" :class="activeTab === item.id ? 'opacity-100' : 'opacity-70'" stroke-width="2.2" />
          {{ item.label }}
        </button>
      </li>
    </ul>

    <div class="mx-3 mt-3 rounded-[16px] border border-black/[0.05] bg-white/60 px-3 py-3 shadow-[0_8px_24px_rgba(15,23,42,0.06)] dark:border-white/[0.06] dark:bg-white/[0.04]">
      <div class="text-[10px] font-bold uppercase tracking-[0.2em] text-ios-textSecondary dark:text-ios-textSecondaryDark">
        MITM 概况
      </div>
      <div class="mt-2 flex items-center justify-between">
        <div>
          <div class="text-[18px] font-extrabold leading-none text-ios-text dark:text-ios-textDark">
            {{ accountStore.accounts.length }}
          </div>
          <div class="mt-0.5 text-[10px] font-medium text-ios-textSecondary dark:text-ios-textSecondaryDark">
            号池总数
          </div>
        </div>
        <span class="rounded-full bg-ios-blue/10 px-2 py-0.5 text-[9px] font-bold tracking-wide text-ios-blue">
          {{ footerModeLabel }}
        </span>
      </div>

      <!-- 当前活跃 Key -->
      <div class="mt-2 rounded-[12px] bg-black/[0.03] px-2.5 py-1.5 text-[10px] font-medium text-ios-textSecondary dark:bg-white/[0.05] dark:text-ios-textSecondaryDark">
        当前活跃 Key
        <div class="mt-0.5 truncate text-[11px] font-semibold text-ios-text dark:text-ios-textDark" :title="activeSummary">
          {{ activeSummary }}
        </div>
      </div>

      <!-- 当前活跃账号 -->
      <div v-if="activeAccountLabel" class="mt-1.5 flex items-center gap-1 rounded-[12px] bg-ios-blue/[0.06] px-2.5 py-1.5 text-[10px] font-medium text-ios-blue">
        <User class="h-3 w-3 shrink-0" stroke-width="2.4" />
        <span class="truncate" :title="activeAccountLabel">{{ activeAccountLabel }}</span>
      </div>

      <!-- 绑定的对话 -->
      <div v-if="boundSessions.length > 0" class="mt-1.5 rounded-[12px] bg-black/[0.02] px-2.5 py-1.5 dark:bg-white/[0.03]">
        <div class="flex items-center gap-1 text-[9px] font-bold uppercase tracking-[0.15em] text-ios-textSecondary dark:text-ios-textSecondaryDark mb-1">
          <MessageSquare class="h-3 w-3 shrink-0" stroke-width="2.2" />
          绑定对话 ({{ boundSessions.length }})
        </div>
        <ul class="space-y-1">
          <li
            v-for="session in boundSessions"
            :key="session.conv_id_short"
            class="flex items-center gap-1.5 text-[10px] text-ios-text dark:text-ios-textDark"
          >
            <Hash class="h-3 w-3 shrink-0 opacity-40" stroke-width="2" />
            <span class="truncate font-mono" :title="session.conv_id_short">{{ session.conv_id_short }}</span>
            <span class="ml-auto shrink-0 text-[9px] text-ios-textSecondary dark:text-ios-textSecondaryDark">{{ session.request_count }}次</span>
          </li>
        </ul>
      </div>

      <div class="mt-2 flex items-center gap-1.5 rounded-[12px] border border-emerald-500/12 bg-emerald-500/[0.06] px-2.5 py-1.5 text-[10px] font-medium text-emerald-700 dark:text-emerald-300">
        <Shield class="h-3 w-3 shrink-0" stroke-width="2.4" />
        健康 {{ mitmStore.status?.pool_status?.filter((item) => item.healthy).length ?? 0 }} / {{ mitmStore.status?.pool_status?.length ?? 0 }}
      </div>

      <!-- ★ 路由模式胶囊：号池 ↔ 提供商(iOS 风滑动指示条) -->
      <div
        class="no-drag-region relative mt-1.5 flex items-stretch rounded-full border border-black/[0.06] bg-white/80 p-0.5 shadow-sm dark:border-white/[0.08] dark:bg-white/[0.05]"
        role="tablist"
      >
        <span
          class="absolute top-0.5 bottom-0.5 left-0.5 rounded-full shadow-md transition-[transform,background-image,box-shadow] duration-[420ms] ease-[cubic-bezier(0.25,1,0.5,1)]"
          :style="{
            width: 'calc(50% - 2px)',
            transform:
              routeMode === 'providers'
                ? 'translateX(calc(100% + 0px))'
                : 'translateX(0)',
          }"
          :class="
            routeMode === 'providers'
              ? 'bg-gradient-to-b from-violet-500 via-fuchsia-400 to-rose-300 shadow-fuchsia-500/25'
              : 'bg-gradient-to-b from-[#3b82f6] to-ios-blue shadow-ios-blue/25'
          "
        />
        <button
          type="button"
          class="ios-btn relative z-10 flex-1 flex h-6 items-center justify-center gap-1 rounded-full text-[10px] font-bold transition-colors duration-200"
          :class="
            routeMode === 'pool'
              ? 'text-white'
              : 'text-ios-textSecondary hover:text-ios-text dark:text-ios-textSecondaryDark dark:hover:text-ios-textDark'
          "
          :disabled="switchingRouteMode"
          @click="setRouteMode('pool')"
        >
          <Users class="h-2.5 w-2.5" stroke-width="2.6" />
          号池
        </button>
        <button
          type="button"
          class="ios-btn relative z-10 flex-1 flex h-6 items-center justify-center gap-1 rounded-full text-[10px] font-bold transition-colors duration-200"
          :class="
            routeMode === 'providers'
              ? 'text-white'
              : 'text-ios-textSecondary hover:text-ios-text dark:text-ios-textSecondaryDark dark:hover:text-ios-textDark'
          "
          :disabled="switchingRouteMode"
          @click="setRouteMode('providers')"
        >
          <Globe class="h-2.5 w-2.5" stroke-width="2.6" />
          提供商
        </button>
      </div>
    </div>

    <!-- ★ v1.8.0 底部 Help / About 入口 -->
    <div class="mx-3 mt-2 flex gap-1.5">
      <button
        type="button"
        class="no-drag-region flex-1 flex items-center justify-center gap-1 py-1.5 rounded-[10px] text-[11px] font-bold transition-all ios-btn"
        :class="
          activeTab === 'Help'
            ? 'bg-ios-blue text-white shadow-sm'
            : 'bg-black/[0.04] text-gray-600 dark:bg-white/[0.06] dark:text-gray-400 hover:bg-black/[0.08] dark:hover:bg-white/[0.1]'
        "
        @click="emit('update:activeTab', 'Help')"
      >
        <BookOpen class="h-3 w-3" stroke-width="2.4" />
        帮助
      </button>
      <button
        type="button"
        class="no-drag-region flex-1 flex items-center justify-center gap-1 py-1.5 rounded-[10px] text-[11px] font-bold transition-all ios-btn"
        :class="
          activeTab === 'About'
            ? 'bg-rose-500 text-white shadow-sm'
            : 'bg-black/[0.04] text-gray-600 dark:bg-white/[0.06] dark:text-gray-400 hover:bg-black/[0.08] dark:hover:bg-white/[0.1]'
        "
        @click="emit('update:activeTab', 'About')"
      >
        <Heart class="h-3 w-3" stroke-width="2.4" />
        关于
      </button>
    </div>
  </nav>
</template>
